--[[------------------------------------------------------

  # HTG + Power recovery by Expansion + SELEXOL Unit + no H2 injection for P2G option 2


--]]------------------------------------------------------

local osmose = require 'osmose'
local model = osmose.Model 'htg_exp_sel_noh2'
local layers  = require 'ET.pulp.layers'
setmetatable(model.layers,layers.layers_metatable)



model.values={
}

model.software = {'VALI', 'ET/pulp/htg_exp_sel_noh2.bls'}-- (name of soft, name of model)

--gas 

-----------------------------------------------------------------------------------------------------------------------
model:addUnit("gridgas_sell", {type = 'Utility', Description = 'gas grid', addToProblem = 1, Fmin = 0, Fmax = 10000000, Cost2 = 'price_gas'})
model["gridgas_sell"]:addStreams {sell = ms ({'grid_gas', 'in', 1})}

model:addUnit("CHTG",{ type = "Process"}) -- describes the full HYDRO and SALTSEP
    model["CHTG"].Cost1 = 0
	model["CHTG"].Cost2 = 50
	model["CHTG"].Cinv1 = 0
	model["CHTG"].Cinv2 = 'C_HTG'
	model["CHTG"]:addStreams {
	-- HYD
      hyd_c1 =  { tin = function(self) return self.F_1_901_T-273 end ,hin = 'Q_1_901_LOAD',tout = function(self) return self.F_1_902_T-273 end, hout= 0, dtmin= 15,alpha ='h_prod', HC = 'heat'},
      hyd_c2 =  { tin = function(self) return self.F_1_951_T-273 end ,hin = 'QR_1_951_LOAD',tout = function(self) return self.F_1_952_T-273 end,hout=0,dtmin=15, alpha='h_prod', HC = 'heat'},
      hyd_c3 =  { tin = function(self) return self.F_1_952_T-273 end ,hin='QR_1_952_LOAD',tout = function(self) return self.F_1_953_T-273 end,hout=0,dtmin=15, alpha='h_prod', HC = 'heat'},
      hyd_c4 =  { tin = function(self) return self.F_1_953_T-273 end ,hin='QR_1_953_LOAD',tout = function(self) return self.F_1_954_T-273 end,hout=0,dtmin=15, alpha='h_prod', HC = 'heat'},
      hyd_c5 =  { tin = function(self) return self.F_1_954_T-273 end ,hin='QR_1_954_LOAD',tout = function(self) return self.F_1_955_T-273 end,hout=0,dtmin=15, alpha='h_prod', HC = 'heat'},
      hyd_c6 =  { tin = function(self) return self.F_1_955_T-273 end ,hin='QR_1_955_LOAD',tout = function(self) return self.F_1_956_T-273 end,hout=0,dtmin=15, alpha='h_prod', HC = 'heat'},
      hyd_c7 =  { tin = function(self) return self.F_1_956_T-273 end ,hin='Q_1_951_LOAD',tout = function(self) return self.F_1_957_T-273 end,hout=0,dtmin=15, alpha='h_prod', HC = 'heat'},
      hyd_c8 =  { tin = function(self) return self.F_1_957_T-273 end ,hin='Q_1_952_LOAD',tout = function(self) return self.F_1_958_T-273 end,hout=0,dtmin=15, alpha='h_prod', HC = 'heat'},
	  hyd_c9 =  { tin = function(self) return self.F_1_958_T-273 end ,hin='Q_1_953_LOAD',tout = function(self) return self.F_1_959_T-273 end,hout=0,dtmin=15, alpha='h_prod', HC = 'heat'},
	-- SSEP
	  ssep_c1 =  { tin = function(self) return self.F_2_901_T-273 end ,hin= 0,tout = function(self) return self.F_2_902_T-273 end,hout=function(self) return self.Q_2_903_LOAD end,dtmin=15, alpha='h_prod', HC = 'heat'},
	  ssep_c2 =  { tin = function(self) return self.F_2_902_T-273 end ,hin= 0,tout = function(self) return self.F_2_903_T-273 end,hout=function(self) return self.Q_2_902_LOAD end,dtmin=15, alpha='h_prod', HC = 'heat'},
	  ssep_c3 =  { tin = function(self) return self.F_2_903_T-273 end ,hin= 0,tout = function(self) return self.F_2_907_T-273 end,hout=function(self) return self.Q_2_904_LOAD end,dtmin=15, alpha='h_prod', HC = 'heat'},
 	 Ssep_c2 =  { tin = function(self) return self.F_2_907_T-273 end ,hin='Q_2_911_LOAD',tout = function(self) return self.F_2_911_T-273+25 end,hout=0,dtmin=10, alpha='h_prod', HC = 'heat'},
   ssep_out =  rs({'gas_ssep_noh2','out', 'F_2_905_MASSF' , AddToProblem=1}),
	 htg_el = ms({'electricity','in', 'W_0_901_POWER' , AddToProblem=1}),
  black_liquor = rs({'black_liquor','in', 54.211 , AddToProblem=1}),  -- xxx

}

model:addUnit("HTG",{ type = "Process"}) -- represents GAS
    model["HTG"].Cost1 = 0
	model["HTG"].Cost2 = 0
	model["HTG"].Cinv1 = 0
	model["HTG"].Cinv2 = 'C_FLASH_2'
	model["HTG"]:addStreams {
	-- GAS
gas_h1 =  { tin = function(self) return self.F_3_901_T-273 end ,hin='Q_3_901_LOAD',tout = function(self) return self.F_3_902_T-273 end,hout=0,dtmin=15, alpha='h_prod', HC = 'heat'},
	-- CO2_RICH_GAS OUTPUT MASSFLOW
	gas_in =  ms({'gas_ssep_noh2','in', 47.399388, AddToProblem=1}),
	htg_gas_out = ms({'cr_gas_4', 'out', 'F_3_904_MASSF', AddToProblem=1}) ,

}

-- EXPANSION OF GAS FROM GASIFIER (before flash) this represents the whole process in the first flow sheet of EXP LV
model:addUnit("EXSEL_EV",{ type = "Process"})
    model["EXSEL_EV"].Cost1 = 0
	model["EXSEL_EV"].Cost2 = 0
	model["EXSEL_EV"].Cinv1 = 0.1093
	model["EXSEL_EV"].Cinv2 = 'C_VEXP_2'--0.0095 -- ( per power load)
	model["EXSEL_EV"]:addStreams {
	exsel_ex1 =  { tin = function(self) return self.F_4_279B_T-273 end ,hin = 'Q_4_282_LOAD',tout = function(self) return self.F_4_280_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, 
	exsel_ex2 =  { tin = function(self) return self.F_4_284_T-273 end ,hin = 'Q_4_283_LOAD',tout = function(self) return self.F_4_285_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, 
    exsel_gph3 = ms({'exsel_lqph', 'out','F_4_286L_MASSF' , AddToProblem=1}) ,
	exsel_el1 = ms({'electricity', 'out',  'T4_OUT_POWER' , AddToProblem=1}) ,
	exsel_cgas1= ms({'exsel_crude_gas', 'out', 'F_4_286_MASSF', AddToProblem=1}) ,
	exsel_gasco2 = ms({'cr_gas_4', 'in', 42.000000, AddToProblem=1}) ,
}

-- COOLING OF GAS FROM GASIFIER (before flash) this represents the whole process in the second flow sheet of EXP LV
model:addUnit("EXSEL_CV",{ type = "Process"})
    model["EXSEL_CV"].Cost1 = 0
	model["EXSEL_CV"].Cost2 = 0
	model["EXSEL_CV"].Cinv1 = 0.1093
    model["EXSEL_CV"].Cinv2 = 0.0045
    model["EXSEL_CV"]:addStreams {
  exsel_vc1 =  { tin = function(self) return self.F_4_279_BB_T-273 end ,hin = 'Q_4_282B_LOAD',tout = function(self) return self.F_4_280_B_T-273 end, hout= 0, dtmin= 10,alpha =5,  HC = 'heat'},
   exsel_lp1 = ms({'exsel_lqph', 'out', 'F_4_286L_MASSF', AddToProblem=1}) ,
    exsel_cgas2= ms({'exsel_crude_gas', 'out', 'F_4_286_MASSF', AddToProblem=1}) ,
	exsel_gasco2 = ms({'cr_gas_4', 'in', 0, AddToProblem=1}) ,
}

-- LIQUID PHASE, EXPANSION/COOLING this represents the whole process in the third flow sheet of EXP LV
model:addUnit("EXSEL_EL",{ type = "Process"})
    model["EXSEL_EL"].Cost1 = 0
	model["EXSEL_EL"].Cost2 = 0
	model["EXSEL_EL"].Cinv1 = 0.1093
	model["EXSEL_EL"].Cinv2 = 'C_LEXP_2'--0.0095 -- ( per power load)
	model["EXSEL_EL"]:addStreams {
 	exsel_lex1 =  { tin = function(self) return self.F_4_280_C_T-273 end ,hin = 'Q_4_282C_LOAD',tout = function(self) return self.F_4_281_C_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, 
    exsel_lex2 =  { tin = function(self) return self.F_4_282_C_T-273 end ,hin = 'Q4_283C_POWER',tout = function(self) return self.F_4_284_C_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, 
	exsel_lp2 = ms({'exsel_lqph', 'in','42.000000', AddToProblem=1}) ,
 	exsel_el1l = ms({'electricity', 'out', function(self) return self.W_LP1_POWER*(-1) + self.W_LP2_POWER*(-1) end, AddToProblem=1}) ,
	exsel_ofg1 = ms({'exsel_ofg1','out','F_4_288_C_MASSF',AddToProblem=1}) ,


}


-- SELEXOL SEPARATOR
model:addUnit("EXSEL_SEL",{ type = "Process"})
    model["EXSEL_SEL"].Cost1 = 0
	model["EXSEL_SEL"].Cost2 = 0
	model["EXSEL_SEL"].Cinv1 = 4.4154
	model["EXSEL_SEL"].Cinv2 = 'C_SEL_2'--0.8257 --(per massfin)
    model["EXSEL_SEL"]:addStreams {
	
exsel_cgas1= ms({'exsel_crude_gas', 'in', 9, AddToProblem=1}) ,
	exsel_slx_h1 =  { tin = function(self) return self.F_3_224_T-273 end ,hin = 'Q_3_201_LOAD',tout = function(self) return self.F_3_230_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, 
    exsel_slx_el = ms({'electricity', 'out', 'W_3_221_POWER', AddToProblem=1}) ,
	exsel_gas = ms({'grid_gas', 'out', function(self) return self.F_3_301_MASSF*3600 end, AddToProblem=1}) ,
	exsel_ofg2 = ms({'exsel_ofg2','out','F_3_305_MASSF',AddToProblem=1}) ,
}


model:addUnit("EXSEL_B1",{ type = "Process"})  -- Calculates thermal energy needed for HTG
    model["EXSEL_B1"].Cost1 = 0
	model["EXSEL_B1"].Cost2 = 0
	model["EXSEL_B1"].Cinv1 = 0.0244
	model["EXSEL_B1"].Cinv2 = 'C_B1_2'--0.0036 --(per hload)
    model["EXSEL_B1"]:addStreams {
	b1_h1 =  { tin = function(self) return self.CP1C_T-273 end ,hin = 'RAD_1_LOAD',tout = function(self) return self.CP1C_T-274 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
	b1_h2 =  { tin = function(self) return self.CP1C_T-274 end ,hin = 'CONV_1_LOAD',tout = function(self) return self.CP1D_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exsel_b1_cgas = ms({'exsel_crude_gas', 'in', 0, AddToProblem=1}) ,
}



model:addUnit("EXSEL_B2",{ type ="Process"}) -- burns vapor from liquid VL separation
    model["EXSEL_B2"].Cost1 = 0
	model["EXSEL_B2"].Cost2 = 0
	model["EXSEL_B2"].Cinv1 = 0.0244
	model["EXSEL_B2"].Cinv2 = 'C_B2_2'--0.0036 --(per hload)
    model["EXSEL_B2"]:addStreams {
	
	b2_h1 =  { tin = function(self) return self.CP2C_T-273 end ,hin = 'RAD_2_LOAD',tout = function(self) return self.CP2C_T-274 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
	b2_h2 =  { tin = function(self) return self.CP2C_T-274 end ,hin = 'CONV_2_LOAD',tout = function(self) return self.CP2D_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exsel_b2_ofg1 = ms({'exsel_ofg1', 'in', 0, AddToProblem=1}) ,
}

model:addUnit("EXSEL_B3",{ type = "Process"}) -- burns stream  from selexol process and gives it to OXP 1
    model["EXSEL_B3"].Cost1 = 0
	model["EXSEL_B3"].Cost2 = 0
	model["EXSEL_B3"].Cinv1 = 0.0244
	model["EXSEL_B3"].Cinv2 = 'C_B3_2'--0.0036 --(per hload)
    model["EXSEL_B3"]:addStreams {
	b3_h1 =  { tin = function(self) return self.CP3C_T-273 end ,hin = 'RAD_3_LOAD',tout = function(self) return self.CP3C_T-274 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
	b3_h2 =  { tin = function(self) return self.CP3C_T-274 end ,hin = 'CONV_3_LOAD',tout = function(self) return self.CP3D_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exsel_b3_ofg2 = ms({'exsel_ofg2', 'in', 2, AddToProblem=1}) ,
}


model:addUnit("EXSEL_OXP1",{ type = "Process"}) -- utility that converts the gas output from the gas separation unit into electricity? xxx There are now two options on what happens with the output from gassep_LP F_4_286: 1: to selexol, 2: to utility. 
    model["EXSEL_OXP1"].Cost1 = 0
	model["EXSEL_OXP1"].Cost2 = 0
	model["EXSEL_OXP1"].Cinv1 = 0.0244
	model["EXSEL_OXP1"].Cinv2 = 'C_OXP1_2'--0.0036 --(per hload)
    model["EXSEL_OXP1"]:addStreams {
	
	exseloxp1_h1 =  { tin = function(self) return self.F_OXP1_12_T-273 end ,hin = 'QR_OXP1_01_LOAD',tout = function(self) return self.F_OXP1_12_T-274 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
	exseloxp1_h2 =  { tin = function(self) return self.F_OXP1_12_T-274 end ,hin = 'QC_OXP1_01_LOAD',tout = function(self) return self.F_OXP1_15_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exselox1_c1 =  { tin = function(self) return self.F_OXP1_02_T-273 end ,hin = 'Q_OXP1_01_LOAD',tout = function(self) return self.F_OXP1_03_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exselox1_c2 =  { tin = function(self) return self.F_OXP1_03_T-273 end ,hin = 'Q_OXP1_02_LOAD',tout = function(self) return self.F_OXP1_04_T-272.9 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exselox1_c3 =  { tin = function(self) return self.F_OXP1_04_T-272.9 end ,hin = 'Q_OXP1_03_LOAD',tout = function(self) return self.F_OXP1_05_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exselox1_ofg2 = ms({'exsel_crude_gas', 'in', 0, AddToProblem=1}) ,
	exselox1_el = ms({'electricity', 'out', 'W_OXP1_04_POWER', AddToProblem=1})
}

model:addUnit("EXSEL_OXP2",{ type = "Process"}) -- utility that converts the gas output from the selexol unit into electricity
    model["EXSEL_OXP2"].Cost1 = 0
	model["EXSEL_OXP2"].Cost2 = 0
	model["EXSEL_OXP2"].Cinv1 = 0.0244
	model["EXSEL_OXP2"].Cinv2 = 'C_OXP2_2'--0.0036 --(per hload)
    model["EXSEL_OXP2"]:addStreams {
	
	exselox2_h1 =  { tin = function(self) return self.F_OXP2_12_T-273 end ,hin = 'QR_OXP2_01_LOAD',tout = function(self) return self.F_OXP2_12_T-274 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
	exselox2_h2 =  { tin = function(self) return self.F_OXP2_12_T-274 end ,hin = 'QC_OXP2_01_LOAD',tout = function(self) return self.F_OXP2_15_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exselox2_c1 =  { tin = function(self) return self.F_OXP2_02_T-273 end ,hin = 'Q_OXP2_01_LOAD',tout = function(self) return self.F_OXP2_03_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exselox2_c2 =  { tin = function(self) return self.F_OXP2_03_T-273 end ,hin = 'Q_OXP2_02_LOAD',tout = function(self) return self.F_OXP2_04_T-272.9 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exselox2_c3 =  { tin = function(self) return self.F_OXP2_04_T-273 end ,hin = 'Q_OXP2_03_LOAD',tout = function(self) return self.F_OXP2_05_T-273 end, hout= 0, dtmin= 10,alpha =5, HC = 'heat'}, --cooling gas product from htg
    exselox2_ofg2 = ms({'grid_gas', 'in', 2, AddToProblem=1}) ,
	exselox2_el = ms({'electricity', 'out', 'W_OXP2_04_POWER', AddToProblem=1})
}


model.inputs = {
 price_gas   = {default = -0.8, unit = 'USD/kWh', description = ''},
h_prod = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
C_HTG_C = {default =1  , min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
C_HTG = {default =10  , min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
h_prod = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'},
C_B1_2 = {default =  63.2041, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_B1_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_B2_2 = {default =  9.69739, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_B2_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_B3_2 = {default =  51.4386, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_B3_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_FLASH_2 = {default =  0.638826, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_FLASH_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_LEXP_2 = {default =  0.030924, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_LEXP_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP1_2 = {default =  29.4713, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP1_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP2_2 = {default =  54.4568, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP2_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_SEL_2 = {default =  0.8257, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_SEL_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_VEXP_2 = {default =  3.17299, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_VEXP_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
A1_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A1_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
A1_IN_WFN2 = {default =  78, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A1_IN_WFO2 = {default =  20.8, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A1_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A2_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A2_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
A2_IN_WFN2 = {default =  78, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A2_IN_WFO2 = {default =  20.8, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A2_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A3_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A3_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
A3_IN_WFH2O = {default =  1.2, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A3_IN_WFO2 = {default =  20.8, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A3_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A4_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A4_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
A4_IN_WFN2 = {default =  78, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A4_IN_WFO2 = {default =  20.8, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A4_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A5_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A5_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
A5_IN_WFN2 = {default =  78, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A5_IN_WFO2 = {default =  20.8, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A5_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A6_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A6_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
A6_IN_WFN2 = {default =  78, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A6_IN_WFO2 = {default =  20.8, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A6_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A7_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A7_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
A7_IN_WFN2 = {default =  78, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A7_IN_WFO2 = {default =  20.8, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
A7_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A8_IN_P = {default =  0, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A8_IN_T = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
A8_IN_WFH2O = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
A8_IN_WFO2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
A8_O_P = {default =  0, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
A_CO2 = {default =  1.4, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
BN_VALI_GS_HP = {default =  2, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
BN_VALI_GS_LHPR = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
BN_VALI_GS_LLPR = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
BN_VALI_GS_LP = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
BN_VALI_GS_LP_SM = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
BN_VALI_GS_VHPR = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
BN_VALI_OXP1 = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
BN_VALI_OXP2 = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
BN_VALI_OXP3 = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CCO23O_EFFIC = {default =  0.82, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CCO2_2O_EFFIC = {default =  0.82, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CH4_REC_ABS = {default =  0.98, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP1C_T = {default =  1300, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP1D_T = {default =  393, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP1E_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP1_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
CP1_WFC1 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP1_WFCO = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP1_WFH2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP2B_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
CP2C_T = {default =  1300, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP2D_T = {default =  393, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP2E_T = {default =  298, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP2_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
CP2_WFC1 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP2_WFCO = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP2_WFH2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP3C_T = {default =  1300, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP3D_T = {default =  393, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP3E_T = {default =  298, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP3_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
CP3_WFC1 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP3_WFCO = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP3_WFH2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP4C_T = {default =  700, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP4D_T = {default =  323, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP4E_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP4_MRC1 = {default =  0, min = 0, max =  0, unit =  'kmol&#x2F;s',   accuracy = 'CST'}, 
CP4_MRCO = {default =  0, min = 0, max =  0, unit =  'kmol&#x2F;s',   accuracy = 'CST'}, 
CP4_MRH2 = {default =  0, min = 0, max =  0, unit =  'kmol&#x2F;s',   accuracy = 'CST'}, 
CP4_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
CP5C_T = {default =  393.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP5_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
CP6C_T = {default =  393.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP6_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
CP7C_T = {default =  393.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
CP7_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
CP7_WFSO2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP8_P = {default =  0, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
CP8_WFC1 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP8_WFCO = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
CP8_WFH2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_3_221_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_B1_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_B2_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_B3_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_CO21B_EFFIC = {default =  0.82, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_CO21O_EFFIC = {default =  0.82, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_CO22B_EFFIC = {default =  0.82, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_CO23B_EFFIC = {default =  0.82, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_CO24B_EFFIC = {default =  0.82, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_FLASH_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_LEXP_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP1_02_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP1_1_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP1_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP2_02_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP2_1_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP2_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP3_02_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_OXP3_1_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_SEL_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
C_VEXP_C = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
DTSS_BOT = {default =  20, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
DTSS_INT = {default =  20, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
DTSS_TOP = {default =  20, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
D_DIPTUBE = {default =  0.025, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
D_EXT = {default =  0.05, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
EA_1_VAR1 = {default =  1, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
EA_2_VAR1 = {default =  0, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
EA_3_VAR1 = {default =  0, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
EA_4_VAR1 = {default =  1, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
EA_5_VAR1 = {default =  10, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
EA_6_VAR1 = {default =  10, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
EA_7_VAR1 = {default =  10, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
EA_8_VAR1 = {default =  0, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F1_IN_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F1_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F1_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F1_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F2_IN_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F2_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F2_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F2_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F3_IN_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F3_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F3_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F3_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F4_IN_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F4_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F4_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F4_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F5_IN_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F5_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F5_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F5_IN_WFCC_COAL = {default =  84.2, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F5_IN_WFH2 = {default =  12.9, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F5_IN_WFH2O = {default =  0, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F5_IN_WFN2 = {default =  0.005, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F5_IN_WFS2 = {default =  0.41, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F5_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F6_IN_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F6_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F6_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F6_IN_WFCC_COAL = {default =  74, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F6_IN_WFH2 = {default =  6.5, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F6_IN_WFH2O = {default =  0, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F6_IN_WFN2 = {default =  0.71, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F6_IN_WFS2 = {default =  1.7, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F6_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F7_IN_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F7_IN_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F7_IN_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F7_IN_WFC_COAL = {default =  79.5, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F7_IN_WFH2 = {default =  9.5, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F7_IN_WFH2O = {default =  0, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F7_IN_WFO2 = {default =  10.3, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F7_IN_WFS2 = {default =  0, min = 0, max =  0, unit =  '%',   accuracy = 'CST'}, 
F7_O_P = {default =  1.01325, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F8_IN_MASSF = {default =  0, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F8_IN_P = {default =  0, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F8_IN_T = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F8_O_P = {default =  0, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
FU_4_353C_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
FU_4_353C_P = {default =  70, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
FU_4_353H_T = {default =  650, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
FU_4_353O_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_0_901_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_0_901_WFC_BM_1 = {default = 0.4934, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, -- changed to BL
F_0_901_WFH_BM_1 = {default =  0.0613, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, -- changed to BL
F_0_901_WFN_BM_1 = {default =  0.0008, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, -- changed to BL
F_0_901_WFO_BM_1 = {default = 0.302795, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, -- changed to BL, i added Na and K content here because I could not figure out how toa add
--F_0_901_WFNa_BM_1 = {default =  0.202, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, -- changed to BL
--F_0_901_WFK_BM_1 = {default = 0.022, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, -- changed to BL
price_el_buy   = {default = 0.06, unit = 'CHF/kWh', description = ''} , -- Julia 
F_0_902_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_0_903_WFH2O = {default =  0.5, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_0_904_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F_0_904_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_0_904_WFC_BM_1 = {default =  0.4085, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_0_904_WFH_BM_1 = {default =  0.0595, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_0_904_WFN_BM_1 = {default =  0.0503, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_0_904_WFS_BM_1 = {default =  0.0046, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_0_905_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_0_906_WFH2O = {default =  0.5, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_0_907_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_0_908_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_0_908_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_0_908_WFH2O = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_0_909_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F_0_909_P = {default =  300, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_1_901_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F_1_902_T = {default =  530, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_1_903_WFC_BM_1 = {default =  0.627, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_1_903_WFH_BM_1 = {default =  0.06, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_1_907_T = {default =  623.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_1_952_T = {default =  550, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_1_953_T = {default =  575, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_1_954_T = {default =  585, min = 0, max =  0, unit =  'K',   accuracy = 'CST'},
F_1_955_T = {default =  605, min = 0, max =  0, unit =  'K',   accuracy = 'CST'},
F_1_956_T = {default =  615, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_2_901_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F_2_903_T = {default =  703, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_2_911_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_2_912_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_2_913_WFH2O = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_3_201_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F_3_201_P = {default =  70, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_3_201_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_3_211_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_3_213_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_3_221_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_3_223_MFCO = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_3_223_MFH2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_3_230_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_3_250_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_3_300_MFC1 = {default =  0.92, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_3_301_MFC1 = {default =  0.96, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_3_305_P = {default =  20, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_3_903_MFCO = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_3_903_MFH2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_3_904_T = {default =  673.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_4_279_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F_4_280_T = {default =  853, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_4_281_B_P = {default =  70, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_4_281_B_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_4_281_C_T = {default =  300.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_4_282_C_P = {default =  70, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_4_284_C_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_4_284_P = {default =  70, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_4_285_C_P = {default =  20, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_4_285_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_4_286_C_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP1_01_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP1_01_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP1_03_VAPF = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP1_04_VAPF = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP1_05_T = {default =  673.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP1_06_MFO2 = {default =  0.21, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP1_06_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP1_06_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP1_09_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F_OXP1_10_MFC1 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP1_10_MFO2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP1_10_P = {default =  20, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP1_10_T = {default =  1400, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP1_11_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP1_12_T = {default =  1300, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP1_13_MFO2 = {default =  0.21, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP1_13_T = {default =  393.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP1_14_T = {default =  1300, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP1_15_T = {default =  393.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP2_01_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP2_01_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP2_03_VAPF = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP2_04_VAPF = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP2_05_T = {default =  673.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP2_06_MFO2 = {default =  0.21, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP2_06_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP2_06_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP2_09_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F_OXP2_10_MFC1 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP2_10_MFO2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP2_10_P = {default =  20, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP2_10_T = {default =  1400, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP2_11_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP2_12_T = {default =  1300, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP2_13_MFO2 = {default =  0.21, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP2_13_T = {default =  393.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP2_14_T = {default =  1300, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP2_15_T = {default =  393.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP3_01_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP3_01_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP3_03_VAPF = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP3_04_VAPF = {default =  1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP3_05_T = {default =  673.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP3_06_MFO2 = {default =  0.21, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP3_06_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP3_06_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP3_09_MASSF = {default =  1, min = 0, max =  0, unit =  'kg&#x2F;s',   accuracy = 'CST'}, 
F_OXP3_10_MFC1 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP3_10_MFO2 = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP3_10_P = {default =  20, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP3_10_T = {default =  1400, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP3_11_P = {default =  1, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
F_OXP3_12_T = {default =  1300, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP3_13_MFO2 = {default =  0.21, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
F_OXP3_13_T = {default =  393.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP3_14_T = {default =  1300, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
F_OXP3_15_T = {default =  393.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
HYD_0_P = {default =  170, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
HYD_0_T = {default =  298, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
HYD_COMP_EFFIC = {default =  0.82, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
HYD_P = {default =  220, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
LSEP_WAT_DP = {default =  0, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
L_EXP_1_EFFIC = {default =  1.25, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
L_EXP_2_EFFIC = {default =  1.25, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
O1F_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
O2D_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
O3D_T = {default =  298.15, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
PERMEABILITY_SM = {default =  5.6, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
P_0_901_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
P_3_211_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
P_INJ_GAS_VAR1 = {default =  1.3, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
P_OXP1_01_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
P_OXP2_01_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
P_OXP3_01_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
QR_3_901_LOAD = {default =  0, min = 0, max =  0, unit =  'kW',   accuracy = 'CST'}, 
RELSOL_CO2_C1 = {default =  17.1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
R_3_901B_DTEQ1 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_3_901B_DTEQ2 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_LIGNIN = {default =  0.28, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
R_OLOSS_SS = {default =  0.1, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
R_OXP1_01_DTEQ1 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_OXP1_01_DTEQ2 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_OXP1_01_DTEQ3 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_OXP2_01_DTEQ1 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_OXP2_01_DTEQ2 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_OXP2_01_DTEQ3 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_OXP3_01_DTEQ1 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_OXP3_01_DTEQ2 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_OXP3_01_DTEQ3 = {default =  0, min = 0, max =  0, unit =  'K',   accuracy = 'CST'}, 
R_Q_OXP = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
R_STM_OXP1 = {default =  0.3, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
R_STM_OXP2 = {default =  0.3, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
R_STM_OXP3 = {default =  0.3, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
R_TPH_OXP = {default =  0, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
SELECTIVITY_C1_SM = {default =  22.4, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
SELECTIVITY_CO_SM = {default =  22.4, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
SELECTIVITY_H2_SM = {default =  0.4, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
SEP1_DP = {default =  0, min = 0, max =  0, unit =  'bar',   accuracy = 'CST'}, 
SOLUBILITY_CO2 = {default =  0.18, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
THICKNESS_SM = {default =  1e-007, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
TPA_VAR1 = {default =  500, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
TPF_VAR1 = {default =  299.15, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
TU_4_319_EFFIC = {default =  0.8, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
T_4_1_EFFIC = {default =  0.82, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
U1 = {default =  362, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
U2 = {default =  143, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
U3 = {default =  254, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
U4 = {default =  7, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
X2 = {default =  0.978335, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
X3 = {default =  0.808258, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
X4 = {default =  0.605782, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
X5 = {default =  0.0776049, min = 0, max =  0, unit =  '-',   accuracy = 'CST'}, 
}


model.outputs = {

A1 = {unit = '-}'},  
A1_IN_MASSF = {unit = 'kg&#x2F;s}'},  
A1_IN_WFH2O = {unit = '%}'},  
A1_IN_WRO2 = {unit = 'kg&#x2F;s}'},  
A1_O_HFLOWTOT = {unit = 'kW}'},  
A1_O_MASSF = {unit = 'kg&#x2F;s}'},  
A1_O_T = {unit = 'K}'},  
A2 = {unit = '-}'},  
A2_IN_MASSF = {unit = 'kg&#x2F;s}'},  
A2_IN_WFH2O = {unit = '%}'},  
A2_IN_WRO2 = {unit = 'kg&#x2F;s}'},  
A2_O_MASSF = {unit = 'kg&#x2F;s}'},  
A2_O_T = {unit = 'K}'},  
A3 = {unit = '-}'},  
A3_IN_MASSF = {unit = 'kg&#x2F;s}'},  
A3_IN_WFN2 = {unit = '%}'},  
A3_IN_WRO2 = {unit = 'kg&#x2F;s}'},  
A3_O_MASSF = {unit = 'kg&#x2F;s}'},  
A3_O_T = {unit = 'K}'},  
A4 = {unit = '-}'},  
A4_IN_MASSF = {unit = 'kg&#x2F;s}'},  
A4_IN_WFH2O = {unit = '%}'},  
A4_IN_WRO2 = {unit = 'kg&#x2F;s}'},  
A4_O_MASSF = {unit = 'kg&#x2F;s}'},  
A4_O_T = {unit = 'K}'},  
A5_IN_MASSF = {unit = 'kg&#x2F;s}'},  
A5_IN_WFH2O = {unit = '%}'},  
A5_O_MASSF = {unit = 'kg&#x2F;s}'},  
A5_O_T = {unit = 'K}'},  
A6_IN_MASSF = {unit = 'kg&#x2F;s}'},  
A6_IN_WFH2O = {unit = '%}'},  
A6_O_MASSF = {unit = 'kg&#x2F;s}'},  
A6_O_T = {unit = 'K}'},  
A7_IN_MASSF = {unit = 'kg&#x2F;s}'},  
A7_IN_WFH2O = {unit = '%}'},  
A7_O_MASSF = {unit = 'kg&#x2F;s}'},  
A7_O_T = {unit = 'K}'},  
A8_IN_MASSF = {unit = 'kg&#x2F;s}'},  
A8_IN_WFN2 = {unit = '-}'},  
A8_O_HFLOWTOT = {unit = 'kW}'},  
A8_O_MASSF = {unit = 'kg&#x2F;s}'},  
A8_O_T = {unit = 'K}'},  
ABS_CREC_C1 = {unit = '-}'},  
ABS_CREC_CO2 = {unit = '-}'},  
ABS_REC_C1 = {unit = '-}'},  
ABS_REC_CO2 = {unit = '-}'},  
AREA_SM = {unit = '-}'},  
A_C1 = {unit = '-}'},  
CNV_4_LOAD = {unit = 'kW}'},  
CNV_5_LOAD = {unit = 'kW}'},  
CNV_6_LOAD = {unit = 'kW}'},  
CNV_7_LOAD = {unit = 'kW}'},  
CONV_1_LOAD = {unit = 'kW}'},  
CONV_2_LOAD = {unit = 'kW}'},  
CONV_3_LOAD = {unit = 'kW}'},  
CP1B_MASSF = {unit = 'kg&#x2F;s}'},  
CP1B_P = {unit = 'bar}'},  
CP1B_T = {unit = 'K}'},  
CP1B_WFCO2 = {unit = '-}'},  
CP1B_WFH2O = {unit = '-}'},  
CP1B_WFN2 = {unit = '-}'},  
CP1B_WFO2 = {unit = '-}'},  
CP1F_P = {unit = 'bar}'},  
CP1_A = {unit = 'kJ&#x2F;kmol}'},  
CP1_HFLOWTOT = {unit = 'kW}'},  
CP1_MASSF = {unit = 'kg&#x2F;s}'},  
CP1_MOLF = {unit = 'kmol&#x2F;s}'},  
CP1_T = {unit = 'K}'},  
CP1_WFCO2 = {unit = '%}'},  
CP1_WFH2O = {unit = '%}'},  
CP1_WFN2 = {unit = '%}'},  
CP1_WFO2 = {unit = '%}'},  
CP1_WRCO2 = {unit = 'kg&#x2F;s}'},  
CP2B_T = {unit = 'K}'},  
CP2F_P = {unit = 'bar}'},  
CP2_A = {unit = 'kJ&#x2F;kmol}'},  
CP2_HFLOWTOT = {unit = 'kW}'},  
CP2_MASSF = {unit = 'kg&#x2F;s}'},  
CP2_MOLF = {unit = 'kmol&#x2F;s}'},  
CP2_T = {unit = 'K}'},  
CP2_WFCO2 = {unit = '%}'},  
CP2_WFH2O = {unit = '%}'},  
CP2_WFN2 = {unit = '%}'},  
CP2_WFO2 = {unit = '%}'},  
CP2_WRCO2 = {unit = 'kg&#x2F;s}'},  
CP3B_T = {unit = 'K}'},  
CP3B_WFCO2 = {unit = '-}'},  
CP3B_WFH2O = {unit = '-}'},  
CP3B_WFN2 = {unit = '-}'},  
CP3B_WFO2 = {unit = '-}'},  
CP3F_P = {unit = 'bar}'},  
CP3_A = {unit = 'kJ&#x2F;kmol}'},  
CP3_HFLOWTOT = {unit = 'kW}'},  
CP3_MASSF = {unit = 'kg&#x2F;s}'},  
CP3_MOLF = {unit = 'kmol&#x2F;s}'},  
CP3_T = {unit = 'K}'},  
CP3_WFO2 = {unit = '%}'},  
CP3_WRCO2 = {unit = 'kg&#x2F;s}'},  
CP4B_T = {unit = 'K}'},  
CP4F_P = {unit = 'bar}'},  
CP4_A = {unit = 'kJ&#x2F;kmol}'},  
CP4_HFLOWTOT = {unit = 'kW}'},  
CP4_MASSF = {unit = 'kg&#x2F;s}'},  
CP4_MOLF = {unit = 'kmol&#x2F;s}'},  
CP4_T = {unit = 'K}'},  
CP4_WFO2 = {unit = '%}'},  
CP4_WRCO2 = {unit = 'kg&#x2F;s}'},  
CP5B_T = {unit = 'K}'},  
CP5_A = {unit = 'kJ&#x2F;kmol}'},  
CP5_HFLOWTOT = {unit = 'kW}'},  
CP5_MASSF = {unit = 'kg&#x2F;s}'},  
CP5_MOLF = {unit = 'kmol&#x2F;s}'},  
CP5_T = {unit = 'K}'},  
CP5_WFO2 = {unit = '%}'},  
CP6B_T = {unit = 'K}'},  
CP6_A = {unit = 'kJ&#x2F;kmol}'},  
CP6_HFLOWTOT = {unit = 'kW}'},  
CP6_MASSF = {unit = 'kg&#x2F;s}'},  
CP6_MOLF = {unit = 'kmol&#x2F;s}'},  
CP6_T = {unit = 'K}'},  
CP6_WFO2 = {unit = '%}'},  
CP7B_T = {unit = 'K}'},  
CP7_A = {unit = 'kJ&#x2F;kmol}'},  
CP7_HFLOWTOT = {unit = 'kW}'},  
CP7_MASSF = {unit = 'kg&#x2F;s}'},  
CP7_MOLF = {unit = 'kmol&#x2F;s}'},  
CP7_T = {unit = 'K}'},  
CP7_WFO2 = {unit = '%}'},  
CP8_MASSF = {unit = 'kg&#x2F;s}'},  
CP8_T = {unit = 'K}'},  
CP8_WFO2 = {unit = '%}'},  
C_B1 = {unit = '-}'},  
C_B2 = {unit = '-}'},  
C_B3 = {unit = '-}'},  
C_FLASH = {unit = '-}'},  
C_LEXP = {unit = '-}'},  
C_OXP1 = {unit = '-}'},  
C_OXP2 = {unit = '-}'},  
C_SEL = {unit = '-}'},  
C_VEXP = {unit = '-}'},  
DV_VAR1 = {unit = '-}'},  
DV_VAR2 = {unit = '-}'},  
DV_VAR3 = {unit = '-}'},  
DV_VAR4 = {unit = '-}'},  
DV_VAR5 = {unit = '-}'},  
DV_VAR6 = {unit = '-}'},  
DV_VAR7 = {unit = '-}'},  
DV_VAR8 = {unit = '-}'},  
DV_VAR9 = {unit = '-}'},  
ETA_CALC_VAR1 = {unit = '-}'},  
EX_COST_VAR1 = {unit = '-}'},  
EX_COST_VAR2 = {unit = '-}'},  
EX_COST_VAR3 = {unit = '-}'},  
EX_COST_VAR4 = {unit = '-}'},  
EX_COST_VAR5 = {unit = '-}'},  
EX_COST_VAR6 = {unit = '-}'},  
EX_COST_VAR7 = {unit = '-}'},  
F1_IN_HFLOWTOT = {unit = 'kW}'},  
F1_IN_WFC1 = {unit = '-}'},  
F1_IN_WFCO = {unit = '-}'},  
F1_IN_WFCO2 = {unit = '-}'},  
F1_IN_WFH2 = {unit = '%}'},  
F1_O_HFLOWTOT = {unit = 'kW}'},  
F1_O_MASSF = {unit = 'kg&#x2F;s}'},  
F1_O_T = {unit = 'K}'},  
F2_IN_HFLOWTOT = {unit = 'kW}'},  
F2_IN_WFC1 = {unit = '-}'},  
F2_IN_WFCO = {unit = '-}'},  
F2_IN_WFCO2 = {unit = '-}'},  
F2_IN_WFH2 = {unit = '-}'},  
F2_IN_WFH2O = {unit = '-}'},  
F2_O_T = {unit = 'K}'},  
F3_IN_HFLOWTOT = {unit = 'kW}'},  
F3_O_HFLOWTOT = {unit = 'kW}'},  
F3_O_MASSF = {unit = 'kg&#x2F;s}'},  
F3_O_T = {unit = 'K}'},  
F4_IN_HFLOWTOT = {unit = 'kW}'},  
F4_IN_WFC1 = {unit = '-}'},  
F4_IN_WFCO = {unit = '-}'},  
F4_IN_WFCO2 = {unit = '-}'},  
F4_IN_WFH2 = {unit = '-}'},  
F4_O_HFLOWTOT = {unit = 'kW}'},  
F4_O_MASSF = {unit = 'kg&#x2F;s}'},  
F4_O_T = {unit = 'K}'},  
F5_IN_HFLOWTOT = {unit = 'kW}'},  
F5_IN_WFO2 = {unit = '%}'},  
F5_O_HFLOWTOT = {unit = 'kW}'},  
F5_O_MASSF = {unit = 'kg&#x2F;s}'},  
F5_O_T = {unit = 'K}'},  
F6_IN_HFLOWTOT = {unit = 'kW}'},  
F6_IN_WFO2 = {unit = '%}'},  
F6_O_HFLOWTOT = {unit = 'kW}'},  
F6_O_MASSF = {unit = 'kg&#x2F;s}'},  
F6_O_T = {unit = 'K}'},  
F7_IN_HFLOWTOT = {unit = 'kW}'},  
F7_IN_WFN2 = {unit = '%}'},  
F7_O_HFLOWTOT = {unit = 'kW}'},  
F7_O_MASSF = {unit = 'kg&#x2F;s}'},  
F7_O_T = {unit = 'K}'},  
F8_O_HFLOWTOT = {unit = 'kW}'},  
F8_O_MASSF = {unit = 'kg&#x2F;s}'},  
F8_O_T = {unit = 'K}'},  
FU_4_353C_T = {unit = 'K}'},  
FU_4_353C_WFC1 = {unit = '-}'},  
FU_4_353C_WFCO = {unit = '-}'},  
FU_4_353C_WFCO2 = {unit = '-}'},  
FU_4_353C_WFH2 = {unit = '-}'},  
FU_4_353O_T = {unit = 'K}'},  
F_0_901_HFLOWTOT = {unit = 'kW}'},  
F_0_901_MASSF = {unit = 'kg&#x2F;s}'},  
F_0_901_WFS_BM_1 = {unit = '-}'},  
F_0_903_MASSF = {unit = 'kg&#x2F;s}'},  
F_0_904_WFO_BM_1 = {unit = '-}'},  
F_0_908_HFLOWTOT = {unit = 'kW}'},  
F_0_908_VOLF = {unit = 'm3&#x2F;s}'},  
F_1_901_T = {unit = 'K}'},  
F_1_901_WFH2O = {unit = '-}'},  
F_1_903_MASSF = {unit = 'kg&#x2F;s}'},  
F_1_903_WFO_BM_1 = {unit = '-}'},  
F_1_951_T = {unit = 'K}'},  
F_1_957_T = {unit = 'K}'},  
F_1_958_T = {unit = 'K}'},  
F_1_959_T = {unit = 'K}'},  
F_2_901_P = {unit = 'bar}'},  
F_2_901_T = {unit = 'K}'},
F_2_902_T = {unit = 'K}'},  
F_2_903_DENSITY = {unit = 'kg&#x2F;m3}'},  
F_2_903_MOLW = {unit = 'kg&#x2F;kmol}'},  
F_2_903_MRH2O = {unit = 'kmol&#x2F;s}'},  
F_2_903_VOLF = {unit = 'm3&#x2F;s}'},  
F_2_903_WFH2O = {unit = '-}'},  
F_2_903_WFH2O_1 = {unit = '-}'},  
F_2_905_DENSITY = {unit = 'kg&#x2F;m3}'},  
F_2_905_MASSF = {unit = 'kg&#x2F;s}'},  
F_2_905_T = {unit = 'K}'},  
F_2_907_T = {unit = 'K}'},  
F_2_913_LHVWT = {unit = 'kJ&#x2F;kg}'},  
F_2_913_MASSF = {unit = 'kg&#x2F;s}'},  
F_3_201A_DENSITY = {unit = 'kg&#x2F;m3}'},  
F_3_201A_MASSF = {unit = 'kg&#x2F;s}'},  
F_3_202_DENSITY = {unit = 'kg&#x2F;m3}'},  
F_3_202_LHVMOL = {unit = 'kJ&#x2F;Nm3}'},  
F_3_202_MASSF = {unit = 'kg&#x2F;s}'},  
F_3_202_MFC1 = {unit = '-}'},  
F_3_202_MFCO = {unit = '-}'},  
F_3_202_MFCO2 = {unit = '-}'},  
F_3_202_MFH2 = {unit = '-}'},  
F_3_202_MOLF = {unit = 'Nm3&#x2F;h}'},  
F_3_202_P = {unit = 'bar}'},  
F_3_202_T = {unit = 'K}'},  
F_3_202_WFC1 = {unit = '-}'},  
F_3_202_WFCO = {unit = '-}'},  
F_3_202_WFCO2 = {unit = '-}'},  
F_3_202_WFH2 = {unit = '-}'},  
F_3_203_MFC1 = {unit = '-}'},  
F_3_203_MFCO2 = {unit = '-}'},  
F_3_203_MFDEPEG = {unit = '-}'},  
F_3_211_VOLF = {unit = 'm3&#x2F;s}'},  
F_3_212_P = {unit = 'bar}'},  
F_3_212_VOLF = {unit = 'm3&#x2F;s}'},  
F_3_213_VOLF = {unit = 'm3&#x2F;s}'},  
F_3_223_MFC1 = {unit = '-}'},  
F_3_223_MFCO2 = {unit = '-}'},  
F_3_223_MOLF = {unit = 'Nm3&#x2F;h}'},  
F_3_224_T = {unit = 'K}'},  
F_3_226_MASSF = {unit = 'kg&#x2F;s}'},  
F_3_226_WFC1 = {unit = '-}'},  
F_3_226_WFCO2 = {unit = '-}'},  
F_3_250_MASSF = {unit = 'kg&#x2F;s}'},  
F_3_301_MASSF = {unit = 'kg&#x2F;s}'},  
F_3_301_UHVWT = {unit = 'kJ&#x2F;kg}'},  
F_3_305_MASSF = {unit = 'kg&#x2F;s}'},  
F_3_305_T = {unit = 'K}'},  
F_3_305_WFC1 = {unit = '-}'},  
F_3_305_WFCO = {unit = '-}'},  
F_3_305_WFCO2 = {unit = '-}'},  
F_3_305_WFH2 = {unit = '-}'},  
F_3_901_MASSF = {unit = 'kg&#x2F;s}'},  
F_3_901_T = {unit = 'K}'},  
F_3_902_T = {unit = 'K}'},  
F_3_904_HFLOWTOT = {unit = 'kW}'},  
F_3_904_MASSF = {unit = 'kg&#x2F;s}'},  
F_3_904_MFC1 = {unit = '-}'},  
F_3_904_MFCO = {unit = '-}'},  
F_3_904_MFCO2 = {unit = '-}'},  
F_3_904_MFH2 = {unit = '-}'},  
F_3_904_MFH2O = {unit = '-}'},  
F_3_904_P = {unit = 'bar}'},  
F_4_279B_T = {unit = 'K}'},  
F_4_279_BB_T = {unit = 'K}'},  
F_4_279_B_MFC1 = {unit = '-}'},  
F_4_279_B_MFCO = {unit = '-}'},  
F_4_279_B_MFCO2 = {unit = '-}'},  
F_4_279_B_MFH2 = {unit = '-}'},  
F_4_279_B_P = {unit = 'bar}'},  
F_4_279_B_T = {unit = 'K}'},  
F_4_279_C_MFC1 = {unit = '-}'},  
F_4_279_C_MFCO = {unit = '-}'},  
F_4_279_C_MFCO2 = {unit = '-}'},  
F_4_279_C_MFH2 = {unit = '-}'},  
F_4_279_C_P = {unit = 'bar}'},  
F_4_279_C_T = {unit = 'K}'},  
F_4_279_MFC1 = {unit = '-}'},  
F_4_279_MFCO = {unit = '-}'},  
F_4_279_MFCO2 = {unit = '-}'},  
F_4_279_MFH2 = {unit = '-}'},  
F_4_279_MFH2O = {unit = '-}'},  
F_4_279_P = {unit = 'bar}'},  
F_4_279_T = {unit = 'K}'},  
F_4_280_B_T = {unit = 'K}'},  
F_4_280_C_T = {unit = 'K}'},  
F_4_282_C_T = {unit = 'K}'},  
F_4_284_T = {unit = 'K}'},  
F_4_285_C_T = {unit = 'K}'},  
F_4_286L_MASSF = {unit = 'kg&#x2F;s}'},  
F_4_286V_VOLF = {unit = 'm3&#x2F;s}'},  
F_4_286_MASSF = {unit = 'kg&#x2F;s}'},  
F_4_287_C_MASSF = {unit = 'kg&#x2F;s}'},  
F_4_288_C_MASSF = {unit = 'kg&#x2F;s}'},  
F_OXP1_02_T = {unit = 'K}'},  
F_OXP1_03_T = {unit = 'K}'},  
F_OXP1_04_T = {unit = 'K}'},  
F_OXP1_07_T = {unit = 'K}'},  
F_OXP1_08_T = {unit = 'K}'},  
F_OXP1_09_LHVWT = {unit = 'kJ&#x2F;kg}'},  
F_OXP1_09_UHVWT = {unit = 'kJ&#x2F;kg}'},  
F_OXP1_11_T = {unit = 'K}'},  
F_OXP1_13_WRO2 = {unit = 'kg&#x2F;s}'},  
F_OXP1_15_WRCO2 = {unit = 'kg&#x2F;s}'},  
F_OXP2_02_T = {unit = 'K}'},  
F_OXP2_03_T = {unit = 'K}'},  
F_OXP2_04_T = {unit = 'K}'},  
F_OXP2_07_T = {unit = 'K}'},  
F_OXP2_08_T = {unit = 'K}'},  
F_OXP2_09_T = {unit = 'K}'},  
F_OXP2_09_WFC1 = {unit = '-}'},  
F_OXP2_09_WFCO = {unit = '-}'},  
F_OXP2_09_WFCO2 = {unit = '-}'},  
F_OXP2_09_WFH2 = {unit = '-}'},  
F_OXP2_11_T = {unit = 'K}'},  
F_OXP2_13_WRO2 = {unit = 'kg&#x2F;s}'},  
F_OXP2_15_WRCO2 = {unit = 'kg&#x2F;s}'},  
F_OXP3_02_T = {unit = 'K}'},  
F_OXP3_03_T = {unit = 'K}'},  
F_OXP3_04_T = {unit = 'K}'},  
F_OXP3_07_T = {unit = 'K}'},  
F_OXP3_08_T = {unit = 'K}'},  
F_OXP3_09_T = {unit = 'K}'},  
F_OXP3_09_WFC1 = {unit = '-}'},  
F_OXP3_09_WFCO = {unit = '-}'},  
F_OXP3_09_WFCO2 = {unit = '-}'},  
F_OXP3_09_WFH2 = {unit = '-}'},  
F_OXP3_11_T = {unit = 'K}'},  
F_OXP3_13_WRO2 = {unit = 'kg&#x2F;s}'},  
F_OXP3_15_WRCO2 = {unit = 'kg&#x2F;s}'},  
HYD_0_MASSF = {unit = 'kg&#x2F;s}'},  
HYD_T = {unit = 'K}'},  
K_C1 = {unit = '-}'},  
K_C1_FLASH = {unit = '-}'},  
K_CO2 = {unit = '-}'},  
K_CO2_FLASH = {unit = '-}'},  
L_BOTTOM = {unit = '-}'},  
L_DIPTUBE = {unit = '-}'},  
L_MIXING = {unit = '-}'},  
N_TH_ABS = {unit = '-}'},  
O1E_P = {unit = 'bar}'},  
O2E_P = {unit = 'bar}'},  
O3E_P = {unit = 'bar}'},  
P_CO2B1_POWER = {unit = 'kW}'},  
P_CO2B2_POWER = {unit = 'kW}'},  
P_CO2B3_POWER = {unit = 'kW}'},  
P_CO2B4_POWER = {unit = 'kW}'},  
P_CO2_O1_POWER = {unit = 'kW}'},  
P_CO2_O2_POWER = {unit = 'kW}'},  
P_CO2_O3_POWER = {unit = 'kW}'},  
P_HYD_POWER = {unit = 'kW}'},  
Q4_283C_POWER = {unit = 'kW}'},  
QBAL_LOAD = {unit = 'kW}'},  
QBC_LOAD = {unit = 'kW}'},  
QC_OXP1_01_LOAD = {unit = 'kW}'},  
QC_OXP2_01_LOAD = {unit = 'kW}'},  
QC_OXP3_01_LOAD = {unit = 'kW}'},  
QD1_LOAD = {unit = 'kW}'},  
QD2_LOAD = {unit = 'kW}'},  
QD3_LOAD = {unit = 'kW}'},  
QD4_LOAD = {unit = 'kW}'},  
QDOXP1_LOAD = {unit = 'kW}'},  
QDOXP2_LOAD = {unit = 'kW}'},  
QDOXP3_LOAD = {unit = 'kW}'},  
QR_1_951_LOAD = {unit = 'kW}'},  
QR_1_952_LOAD = {unit = 'kW}'},  
QR_1_953_LOAD = {unit = 'kW}'},  
QR_1_954_LOAD = {unit = 'kW}'},  
QR_1_955_LOAD = {unit = 'kW}'},  
QR_OXP1_00_LOAD = {unit = 'kW}'},  
QR_OXP1_01_LOAD = {unit = 'kW}'},  
QR_OXP2_00_LOAD = {unit = 'kW}'},  
QR_OXP2_01_LOAD = {unit = 'kW}'},  
QR_OXP3_00_LOAD = {unit = 'kW}'},  
QR_OXP3_01_LOAD = {unit = 'kW}'},  
QU_4_353_LOAD = {unit = 'kW}'},  
Q_1_901_LOAD = {unit = 'kW}'},  
Q_1_951_LOAD = {unit = 'kW}'},  
Q_1_952_LOAD = {unit = 'kW}'},  
Q_1_953_LOAD = {unit = 'kW}'},  
Q_2_902_LOAD = {unit = 'kW}'},  
Q_2_903_LOAD = {unit = 'kW}'},  
Q_2_904_LOAD = {unit = 'kW}'},  
Q_2_911_LOAD = {unit = 'kW}'},  
Q_3_201_LOAD = {unit = 'kW}'},  
Q_3_901_LOAD = {unit = 'kW}'},  
Q_4_282B_LOAD = {unit = 'kW}'},  
Q_4_282C_LOAD = {unit = 'kW}'},  
Q_4_282_LOAD = {unit = 'kW}'},  
Q_4_283_LOAD = {unit = 'kW}'},  
Q_A1_LOAD = {unit = 'kW}'},  
Q_A2_LOAD = {unit = 'kW}'},  
Q_A3_LOAD = {unit = 'kW}'},  
Q_A4_LOAD = {unit = 'kW}'},  
Q_A5_LOAD = {unit = 'kW}'},  
Q_A6_LOAD = {unit = 'kW}'},  
Q_A7_LOAD = {unit = 'kW}'},  
Q_A8_LOAD = {unit = 'kW}'},  
Q_F1_LOAD = {unit = 'kW}'},  
Q_F2_LOAD = {unit = 'kW}'},  
Q_F3_LOAD = {unit = 'kW}'},  
Q_F4_LOAD = {unit = 'kW}'},  
Q_F5_LOAD = {unit = 'kW}'},  
Q_F6_LOAD = {unit = 'kW}'},  
Q_F7_LOAD = {unit = 'kW}'},  
Q_F8_LOAD = {unit = 'kW}'},  
Q_OXP1_01_LOAD = {unit = 'kW}'},  
Q_OXP1_02_LOAD = {unit = 'kW}'},  
Q_OXP1_03_LOAD = {unit = 'kW}'},  
Q_OXP1_04_LOAD = {unit = 'kW}'},  
Q_OXP2_01_LOAD = {unit = 'kW}'},  
Q_OXP2_02_LOAD = {unit = 'kW}'},  
Q_OXP2_03_LOAD = {unit = 'kW}'},  
Q_OXP2_04_LOAD = {unit = 'kW}'},  
Q_OXP3_01_LOAD = {unit = 'kW}'},  
Q_OXP3_02_LOAD = {unit = 'kW}'},  
Q_OXP3_03_LOAD = {unit = 'kW}'},  
Q_OXP3_04_LOAD = {unit = 'kW}'},  
RAD_1_LOAD = {unit = 'kW}'},  
RAD_2_LOAD = {unit = 'kW}'},  
RAD_3_LOAD = {unit = 'kW}'},  
RAD_4_LOAD = {unit = 'kW}'},  
STAGE_CUT_SM = {unit = '-}'},  
T4_OUT_POWER = {unit = 'kW}'},  
T_EXTIN = {unit = '-}'},  
T_EXTM1 = {unit = '-}'},  
T_EXTM2 = {unit = '-}'},  
T_EXTOUT = {unit = '-}'},  
WOBBE_ABS = {unit = '-}'},  
WU_4_353_POWER = {unit = 'kW}'},  
W_0_901_POWER = {unit = 'kW}'},  
W_3_211_POWER = {unit = 'kW}'},  
W_3_212_POWER = {unit = 'kW}'},  
W_3_221_POWER = {unit = 'kW}'},  
W_LP1_POWER = {unit = 'kW}'},  
W_LP2_POWER = {unit = 'kW}'},  
W_OXP1_04_POWER = {unit = 'kW}'},  
W_OXP1_1_POWER = {unit = 'kW}'},  
W_OXP2_04_POWER = {unit = 'kW}'},  
W_OXP2_1_POWER = {unit = 'kW}'},  
W_OXP3_04_POWER = {unit = 'kW}'},  
W_OXP3_1_POWER = {unit = 'kW}'},   
}



return model